### ISSUE TITLE
Error running Schulze_STV from array unexectedly set to NULL

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Condorcet#1]
In the 'Schulze-STV' branch, the new method _Schulze_STV_ is running into errors. Here are the error messages:
```
Fatal error: Uncaught TypeError: end(): Argument #1 ($array) must be of type array, null given in /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php:96
Stack trace:
#0 /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php(96): end(NULL)
#1 /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php(101): CondorcetPHP\Condorcet\Algo\Methods\Schulze\Schulze_STV->addToSet(NULL)
#2 /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php(101): CondorcetPHP\Condorcet\Algo\Methods\Schulze\Schulze_STV->addToSet(Array)
#3 /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php(88): CondorcetPHP\Condorcet\Algo\Methods\Schulze\Schulze_STV->addToSet(Array)
#4 /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php(32): CondorcetPHP\Condorcet\Algo\Methods\Schulze\Schulze_STV->prepareOutcomes()
#5 /home/liam/src/Condorcet/src/ElectionProcess/ResultsProcess.php(83): CondorcetPHP\Condorcet\Algo\Methods\Schulze\Schulze_STV->getResult()
#6 /home/liam/src/Condorcet/src/Console/Commands/ElectionCommand.php(612): CondorcetPHP\Condorcet\Election->getResult('Schulze STV')
#7 /home/liam/src/Condorcet/src/Console/Commands/ElectionCommand.php(412): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->displayMethodsResultSection(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/liam/src/Condorcet/vendor/symfony/console/Command/Command.php(312): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/liam/src/Condorcet/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/liam/src/Condorcet/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(CondorcetPHP\Condorcet\Console\Commands\ElectionCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/liam/src/Condorcet/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/liam/src/Condorcet/src/Console/CondorcetApplication.php(30): Symfony\Component\Console\Application->run()
#13 /home/liam/src/Condorcet/bin/condorcet.php(32): CondorcetPHP\Condorcet\Console\CondorcetApplication::run()
#14 /home/liam/src/Condorcet/bin/condorcet(3): require('/home/liam/src/...')
#15 {main}
  thrown in /home/liam/src/Condorcet/src/Algo/Methods/Schulze/Schulze_STV.php on line 96
```

This is in a recursive function called `addToSet()`. Here's the code (with comments removed):
```
protected function addToSet(array $set)
    {
        $election = $this->getElection();
        $M = $this->M;
        $CandidatesKeys = array_keys($election->getCandidatesList());
        foreach ($CandidatesKeys as $candidate) if ($candidate > end($set))
        {
            array_push($set, $candidate);
            //$set .= $candidate;
            if (count($set) < $M) {
                $set = $this->addToSet($set/*, $M*/);
            } else {
                array_push($this->outcomes, $set);
            }
        }
    }
```
The problem is in the `end()` function. The strange thing is that `$set` does not appear to be set to NULL earlier in the `addToSet` function. In fact, the function runs fine the first times. It's possible to remove this error from line 96 by adding a line before that says `$prev = end($set)` & replacing `($candidate > end($set))` with `($candidate > $prev)`. However, this only delays the problem to line 98, where there's an error in `array_push($set, $candidate)`.

So somehow `$set` is becoming NULL only when the `foreach` loop begins, but not every time. I cannot think of any explanation for why this happens. Hopefully @julien-boudry will know.

**Comment by LiamM32** [comment]
I solved this and many other bugs & errors in the latest commits. I'm more productive at debugging now that I am using the free trial of PhpStorm.
